### ISSUE TITLE
Visualising the data of version:virtual labs feedback v1.0

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/analytics-dashboard#9]
we need to display the count of the feedback responses of version:virtual labs feedback v1.0.

**Comment by travula** [comment]
@reenamadamwar @vlead/vlead-staff 
Why are all the issues closed?  There should be some notes on resolution or an artefact that is realized.

Can you please deploy your service on base4 for others to look at it?

**Comment by reenamadamwar** [comment]
Requirements are changed. Now we are not visualizing by single single version. That's why closed these issues and created new one.
